# Assignment-4 

### Regno.:20MAI0056

### Name : Shubham Muley

Github link to repository : [Machine-Learning-Course](https://github.com/shubham-muley/Machine-Learning-Course)

# Logistic Regression

In [2]:
#Import the required libraries

import numpy as np
import pandas as pd

In [3]:
#To ignore the Warnings which are occured while we preprocess the dataframes

import warnings
warnings.filterwarnings("ignore")

In [4]:
#Read the dataset onto a variable

train = pd.read_csv('Data/titanic_data.csv')
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
train.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [6]:
# Fix the Predictor Variables
data = train[['Survived','Pclass','Sex','Age','Fare']]

In [7]:
# categorical encoding

data['Sex'] = data['Sex'].apply(lambda sex:1 if sex=="male" else 0)

In [8]:
data['Sex']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [9]:
#Handling missing values
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       714 non-null    float64
 4   Fare      891 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 34.9 KB


In [10]:
print(data['Age'].isnull().sum())

177


In [11]:
data["Age"]= data["Age"].fillna(data['Age'].median())

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       891 non-null    float64
 4   Fare      891 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 34.9 KB


In [13]:
data['Age'] = data['Age'].astype('int64')

In [14]:
# Take a look at dataframe

print(data.head())
print(data.shape)

   Survived  Pclass  Sex  Age     Fare
0         0       3    1   22   7.2500
1         1       1    0   38  71.2833
2         1       3    0   26   7.9250
3         1       1    0   35  53.1000
4         0       3    1   35   8.0500
(891, 5)


In [15]:
# Set the predictor(X) and Response(Y) Variables

X = data.drop("Survived",axis=1)
Y = data['Survived']

In [16]:
# spliting into training and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test = train_test_split(X,Y, test_size=0.25, stratify = Y,random_state=25)

# Logistic regression

In [17]:
# call logistic regression Model
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()
logit.fit(X_train,Y_train)

LogisticRegression()

In [18]:
# compute the Predictions or Y hat
Y_pred = logit.predict(X_test)

In [19]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)
cm

array([[115,  22],
       [ 25,  61]], dtype=int64)

In [20]:
#Accuracy Score
from sklearn.metrics import accuracy_score
lr_accuracy = accuracy_score(Y_test, Y_pred)
lr_accuracy

0.7892376681614349

In [21]:
# Classification Report 
from sklearn.metrics import classification_report 
report = classification_report(Y_test, Y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.82      0.84      0.83       137
           1       0.73      0.71      0.72        86

    accuracy                           0.79       223
   macro avg       0.78      0.77      0.78       223
weighted avg       0.79      0.79      0.79       223



# Naive Bayes

In [22]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [23]:
classifier= GaussianNB()
classifier.fit(X_train, Y_train)

classifier.class_prior_

array([0.61676647, 0.38323353])

In [24]:
predicts=classifier.predict(X_test)
cm = confusion_matrix(Y_test, predicts)
print(cm)

[[106  31]
 [ 24  62]]


In [25]:
GNB_accuracy=accuracy_score(predicts,Y_test)
print(GNB_accuracy*100)

75.33632286995515


### Logistic Regression has more accuracy than naive bayes

In [26]:
print("Gaussian Naive Bayes",GNB_accuracy*100)
print("Logistic Regression",lr_accuracy*100)

Gaussian Naive Bayes 75.33632286995515
Logistic Regression 78.9237668161435
